apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-broker-rolebinding
  namespace: tsb-ns
subjects:
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: ${USER_ID}
- kind: ServiceAccount
  name: tsb-account
roleRef:
  kind: Role
  name: service-broker-role
  apiGroup: rbac.authorization.k8s.io
