apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-broker-role
  namespace: tsb-ns
rules:
- apiGroups: ['']
  resources: ['*']
  verbs: ['*']
- apiGroups: ['apps']
  resources: ['*']
  verbs: ['*']
- apiGroups: ["tmax.io"]
  resources: ["templates","templateinstances"]
  verbs: ["*"]
- apiGroups: ["tmax.io"]
  resources: ["catalogserviceclaims"]
  verbs: ["get","list","create","delete"]
- apiGroups: ["servicecatalog.k8s.io"]
  resources: ["*"]
  verbs: ["*"]