kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-broker-cluster-rolebinding-{tsbNamespace}
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: ${USER_ID}
  - kind: ServiceAccount
    name: tsb-account
    namespace: {tsbNamespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: service-broker-cluster-role