kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-broker-cluster-role
rules:
- apiGroups: ["servicecatalog.k8s.io"]
  resources: ["clusterserviceclasses","clusterserviceplans"]
  verbs: ["get","list"]