apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cluster-template-service-broker
  name: cluster-template-service-broker
  namespace: cluster-tsb-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-template-service-broker
  template:
    metadata:
      labels:
        app: cluster-template-service-broker
    spec:
      serviceAccountName: cluster-tsb-sa
      containers:
      - image: tmaxcloudck/cluster-tsb:0.0.1
        name: cluster-tsb
        imagePullPolicy: Always